version: '2'

services:
  backend:
    container_name: lasvecka-python
    build:
      context: ./lasvecka-python
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/lasvecka-python

  frontend:
    container_name: lasvecka-react
    build:
      context: ./lasvecka-react
      dockerfile: dev.Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/lasveckor/frontend
