version: '2'

services:
  backend:
    container_name: lasvecka-python
    build:
      context: ./lasvecka-python
      dockerfile: dev.Dockerfile
    network_mode: "nginxreverseproxy_default"
    volumes:
      - ./backend:/lasvecka-python
    environment:
      VIRTUAL_HOST: api.lasvecka.nu
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: api.lasvecka.nu

  frontend:
    container_name: lasvecka-react
    build:
      context: ./lasvecka-react
      dockerfile: prod.Dockerfile
    stdin_open: true
    network_mode: "nginxreverseproxy_default"
    volumes:
      - ./frontend:/usr/src/lasveckor/frontend
    environment:
      VIRTUAL_HOST: test.chs.se
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: test.chs.se
