version: '3'

services:
  app:
    container_name: lasvecka-node
    iamge: ghcr.io/gudchs/lasvecka:main
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - lasvecka:/usr/src/app/data

volumes:
  lasvecka:
