name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Setup Docker build
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./lasvecka-python/prod.Dockerfile
          push: true
          tags: gudchs/lasvecka_backend:latest
          
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./lasvecka-react/prod.Dockerfile
          push: true
          tags: gudchs/lasvecka_frontend:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
